version: "3.7"

services:
  db:
    image: mysql:latest
    container_name: restaurantFlow
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: restaurantFlow
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
